preload = /home/gambs/wallpapers/Black.jpg

# Aplica aos monitores (sem espaços após a vírgula)
wallpaper = DP-1,/home/gambs/Wallpapers/Black.jpg
wallpaper = HDMI-A-1,/home/gambs/Wallpapers/Black.jpg
